### ISSUE TITLE
MQTT & Database

### ISSUE THREAD

**Issue by afeezaziz** [flespi-software/flespi_pipeline#1]
Hi,

1. Can you write a  tutorial on how to capture data continuously from a channel?

2. Then how to actually do something with the data e.g. print it or store it in database.

**Comment by janbartnitsky** [comment]
afeezaziz,
You can just edit flespi_pipeline.py in the following way:
1. edit fields channel_id (with id of a channel to subscribe) and username (with valid flespi token)
2. replace the function **on_messge()** with the following:
`def on_message(client, topic, payload, qos, properties):
    print(topic, payload)` 
each new message in a channel will call **on_message()** function
